language: java

before_install:

#script: ./ci-build.sh

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk9
##  - oraclejdk10 now deprecated
#  - oraclejdk11
#  - openjdk8
#  - openjdk9
#  - openjdk10
#  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
